name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ["test"]
        ruby: ['3.1', '3.2', '3.3']
        include:
        - ruby: 3.1 # keep in sync with lowest version, .rubocop.yml, and gemspec
          task: rubocop
    name: ${{ matrix.ruby }} rake ${{ matrix.task }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake ${{ matrix.task }}
